# Generated by Django 4.2.6 on 2023-10-21 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("player", "root_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="dir",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dir",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("efaae1d9-27c7-4d0f-840f-384e760becb4"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("459df778-3cd1-41fb-af68-655a8d7517de"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("af613ca7-5b31-4ad4-b8e3-a51f1d104889"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("c53462c5-ed5c-4cf3-9a33-17050619d40c"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
    ]
