# Generated by Django 4.2.6 on 2023-10-21 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_dir_updated_alter_dir_code_alter_file_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dir",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("97fa9f03-3822-4edd-aa8b-3fb84f7317d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("4ec4faa7-281a-4c3b-a417-1792cf261959"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="player.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("6667968b-fdc3-4966-b54b-b9291f8bf6f4"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("d709e4ba-4312-442f-8f11-c239e99c4263"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
    ]
