# Generated by Django 4.2.6 on 2023-10-21 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_alter_dir_code_alter_file_code_alter_file_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dir",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Код",
            ),
        ),
    ]
